allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://storage.googleapis.com/download.flutter.io'
        }
    }
}

rootProject.buildDir = '../build'

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
    afterEvaluate { project ->
        if (project.hasProperty('android')) {
            project.android {
                if (namespace == null) {
                    if (project.name == "flutter_bluetooth_serial") {
                        namespace = "io.github.edufolly.flutterbluetoothserial"
                    } else if (project.name == "floating") {
                        namespace = "xyz.wrbl.floating"
                    } else {
                        namespace = project.group
                    }
                }
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
